services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_server
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    user: root
    network_mode: host
  grafana:
    image: grafana/grafana
    container_name: grafana_server
    volumes:
      - ./grafana-storage:/var/lib/grafana
    user: root
    network_mode: host
    depends_on:
    - prometheus
    - graphite
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite_server
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep -q 2003"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    network_mode: host